name: hand_control
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.*
  - pip>=23.0
  - numpy>=1.23.0
  - opencv
  - matplotlib
  - scipy>=1.10.0
  - pydantic>=1.10.0,<2.0.0
  - pytest>=7.0.0
  - pip:
    - pynput>=1.7.0
    - mediapipe>=0.10.0
    - "wilor-mini @ git+https://github.com/Joeclinton1/WiLoR-mini"
    - lerobot>=0.1.0
    - ruff>=0.1.0